services:
  fastapi:
    #image: ghcr.io/etalab-ia/whisper-openai-api/app:latest
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8000:8000
    volumes:
      - .:/home/whisper
